### ISSUE TITLE
display bug on Hyper term

### ISSUE THREAD

**Issue by acarl005** [asciimoo/wuzz#23]
It looks great on MacOS terminal and iTerm2. There seems to be a problem with whitespace on [Hyper](https://hyper.is/) term.
![image](https://cloud.githubusercontent.com/assets/8334252/22663247/c40f73ec-ec60-11e6-9a0c-0b1fe34b824c.png)

**Comment by Eraden** [comment]
Also <kbd>CTRL</kbd> <kbd>R</kbd> for linux version is not working in URL section.

**Comment by Eraden** [comment]
This is most certain hyper bugs because I checked this in following terminals:

* konsole
* sakura
* xterm
* hyper

Also you checked this on:

* iTerm2
* terminal.app

And only `hyper` has this problem. Besides `hyper` term can't handle properly changing font, example:

![image](https://cloud.githubusercontent.com/assets/970831/22728976/df393c8a-ede0-11e6-977c-ed8b0005bfdd.png)

Font family: Deja Vu Serif, Deja Vu Sans, Deja Vu Sans Mono
Font size: 12

Cursor is this purple thing in middle of nowere. After this simple change `wuzz` became unsuable:

![image](https://cloud.githubusercontent.com/assets/970831/22729010/155da864-ede1-11e6-82e4-387986288311.png)

**Comment by Benaiah** [comment]
@Eraden thanks for checking in - I suspected it was a bug in hyper, given there have been no reports from users with other terminals. I doubt that there's anything we can do in wuzz to fix this, especially without affecting the working behavior in most terminals. Given that, I'm going to close this issue.

@acarl005, please feel free to let me know if you don't think that's an accurate take on the bug, or if you have a suggestion as to how it could be fixed. I'd be happy to reopen the issue if there's something we can do about it.
