### ISSUE TITLE
Save requests

### ISSUE THREAD

**Issue by dbogatov** [asciimoo/wuzz#65]
Hi,

First of all, thank you for the utility. It is just great!

I wanted to propose a feature (which will let me forget about CocoaRest app) of saving requests (with its parameters.

Usually, how I use the utility, I have some small number of requests that have to work on my API.
I test my API (same endpoints) with the utility until they work.

It would be much easier for me if I could save the requests.

Thank you!

**Comment by zbb93** [comment]
I may take a stab at this later today/tomorrow. I was thinking something along the lines of `wuzz -o /path/to/file` will open the app with all of the windows populated. Just `CTRL + r` to run the request. Additionally I was thinking it may also be nice to have a feature where as requests are made they are stored in a history. Then if you wanted to execute a previously executed command you could use the arrow keys or something to navigate through previously executed requests. What do you guys think?

**Comment by Dima4ka** [comment]
I like these proposals!

As for `wuzz -o /path/to/file`, it would be nice if that config contained multiple request infos, or the full "history".

As for the history itself, sometimes I do stupid typos or just figure out a correct way of making a request. So I would not store each an every request, but rather the latest for the given unique URL.

I do love `Ctrl + r` idea! It is so annoying to press multiple TABs back and forth.

Finally, given that the tool has sophisticated internal request mechanisms, would it be possible to introduce command line arguments like `--method PUT`, `--data param=val`, `--url http://smth.com` and so on. Additionally tool returns 0 for 200+ response and not 0 otherwise. If it is implemented, I would be able to use a tool in my test pipeline.

**Comment by colinta** [comment]
Now that #74 is merged, seems like this issue could be closed... I wanted to ask before that, though: how do we *load* a previous request?  Now that I've got my `Authorization: Bearer ...` and url and params set, it would be nice to be able to restore the request I saved.

Looking at the code now, but I'm not a go developer, so
![no idea what im doing](https://user-images.githubusercontent.com/27570/28438473-69542d5e-6d5b-11e7-9e39-f8b8f88ffc49.jpg)

**Comment by colinta** [comment]
Ahha, `wuzz -f saved-request`.

**Comment by marderchen** [comment]
MEOW! reveived the cute mailthingi.. and preparing a purr back maybe it takes a while
=^.^=
